In [2]:
import numpy as np
import pandas as pd
import os
from pathlib import  Path
path = r"H:\202304_202407_guage\pre_hor\pre_hor_20230601000000.csv"
# path = r"H:\202304_202407_guage\pre_hor\pre_hor_20230801000000.csv"
df = pd.read_csv(path,header=None, low_memory=False)
df_new=pd.DataFrame()
df_new['station']=df[0]  
df_new['province']=df[1]
df_new['cnty']=df[4]
df_new["lon"] = df[11]
df_new["lat"] = df[10]
df_new["pre"] = df[14]
df_new["city"] = df[3]
df_new = df_new.drop(index=[0])  # 删第一行
df_new["lon"] = df_new["lon"].map(float)
df_new["lat"] = df_new["lat"].map(float)
df_new["pre"] = df_new["pre"].map(float)

df_clear = df_new.drop(
    df_new[#(df_new["pre"] > 888888) | 
        (df_new["lon"] > 122) |
        (df_new["lon"] < 111) |
        (df_new["lat"] > 37) |
        (df_new["lat"] < 30) 
    ].index
)
df_reset = df_clear.reset_index(drop=True)

In [3]:
path = r"H:\202304_202407_guage\pre_hor\pre_hor_20230601000000.csv"
# path = r"H:\202304_202407_guage\pre_hor\pre_hor_20230801000000.csv"
df = pd.read_csv(path,header=None, low_memory=False)

In [4]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Station_Name,Province,Country,City,Cnty,Town_code,Town,Station_levl,Station_Id_C,Station_Id_d,Lat,Lon,Alti,Datetime,PRE_1h,Q_PRE_1h
1,三联,广西壮族自治区,中国,河池市,巴马瑶族自治县,NaN,NaN,14,N8014,788014,24.2231,107.5319,523,2023-06-01 00:00:00,0,0
2,静海西翟庄,天津市,中国,天津市,静海区,NaN,NaN,14,A2506,652506,38.7733,117.0039,4.6,2023-06-01 00:00:00,0,0
3,长泰岩溪林场,福建省,中国,漳州市,长泰区,NaN,NaN,14,F6085,706085,24.7722,117.7547,73,2023-06-01 00:00:00,0,0
4,忻城安东,广西壮族自治区,中国,来宾市,忻城县,NaN,NaN,14,N2536,782536,24.03,109.0017,174,2023-06-01 00:00:00,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72900,西岗大连森林动物园,辽宁省,中国,大连市,西岗区,NaN,NaN,14,L2731,762731,38.8817,121.6058,47.5,2023-06-01 00:00:00,0,0
72901,汶上阳城煤矿,山东省,中国,济宁市,汶上县,NaN,NaN,14,D9041,689041,35.7714,116.3192,39.3,2023-06-01 00:00:00,0,0
72902,合作勒秀常规站,甘肃省,中国,甘南藏族自治州,合作市,NaN,NaN,16,W9530,879530,34.7089,102.9997,2799,2023-06-01 00:00:00,0,0
72903,巍山五印,云南省,中国,大理白族自治州,巍山彝族回族自治县,NaN,NaN,14,T6929,846929,25.1522,100.1283,1612.2,2023-06-01 00:00:00,0,0
72904,长海獐子岛,辽宁省,中国,大连市,长海县,NaN,NaN,13,54578,54578,39.0367,122.7114,57.3,2023-06-01 00:00:00,0,0

In [ ]:
df_reset

        station province cnty       lon      lat       pre
0        宁洛K256      安徽省  蒙城县  116.6983  33.1431       0.0
1        连云东辛农场      江苏省  市辖区  119.3094  34.5614       0.0
2           狼城岗      河南省  中牟县  114.1297  34.8331       0.0
3            韩寺      河南省  中牟县  114.1347  34.6258       0.0
4            石象      河南省  长葛市  113.8681  34.1922       0.0
...         ...      ...  ...       ...      ...       ...
13958        石弓      安徽省  涡阳县  116.3844  33.6947       0.0
13959        园林      湖北省  潜江市  112.8725  30.4350       0.0
13960  蚌合下行K119      安徽省  长丰县  117.1011  31.9922  999999.0
13961        阚疃      安徽省  利辛县  116.2814  33.0181       0.0
13962    汶上阳城煤矿      山东省  汶上县  116.3192  35.7714       0.0

[13963 rows x 6 columns]

In [5]:
#筛选没有漏测的地基站点

dirpath_data = Path(r"H:\202304_202407_guage\pre_hor")
path = r"H:\202304_202407_guage\pre_hor"
files = os.listdir(path)

all_lon_lat=set(list(zip(df_reset['lon'], df_reset['lat'])))

i = 0  # i为file计数
for file in files:
    print(file)
    i += 1
    filepath = dirpath_data / file
    if int(file[8:18])<2023050100:
        continue
    if int(file[8:18])>=2024050100:
        break
    df = pd.read_csv(filepath,  header=None, low_memory=False, usecols=[10, 11, 14], skiprows=[0],dtype=float)
    lat, lon ,pre= df[10].values, df[11].values,df[14].values
    lat=lat[pre<888888]
    lon=lon[pre<888888]
    lon_lat = list(zip(lon, lat))
    lon_lat_set = set(lon_lat)

    all_lon_lat=all_lon_lat.intersection(lon_lat_set)


new_lons = [coord[0] for coord in all_lon_lat]
new_lats = [coord[1] for coord in all_lon_lat]

pre_hor_20230401000000.csv
pre_hor_20230401010000.csv
pre_hor_20230401020000.csv
pre_hor_20230401030000.csv
pre_hor_20230401040000.csv
pre_hor_20230401050000.csv
pre_hor_20230401060000.csv
pre_hor_20230401070000.csv
pre_hor_20230401080000.csv
pre_hor_20230401090000.csv
pre_hor_20230401100000.csv
pre_hor_20230401110000.csv
pre_hor_20230401120000.csv
pre_hor_20230401130000.csv
pre_hor_20230401140000.csv
pre_hor_20230401150000.csv
pre_hor_20230401160000.csv
pre_hor_20230401170000.csv
pre_hor_20230401180000.csv
pre_hor_20230401190000.csv
pre_hor_20230401200000.csv
pre_hor_20230401210000.csv
pre_hor_20230401220000.csv
pre_hor_20230401230000.csv
pre_hor_20230402000000.csv
pre_hor_20230402010000.csv
pre_hor_20230402020000.csv
pre_hor_20230402030000.csv
pre_hor_20230402040000.csv
pre_hor_20230402050000.csv
pre_hor_20230402060000.csv
pre_hor_20230402070000.csv
pre_hor_20230402080000.csv
pre_hor_20230402090000.csv
pre_hor_20230402100000.csv
pre_hor_20230402110000.csv
pre_hor_20230402120000.csv
pre_hor_20230402130000.csv
pre_hor_20230402140000.csv
pre_hor_20230402150000.csv
pre_hor_20230402160000.csv
pre_hor_20230402170000.csv
pre_hor_20230402180000.csv
pre_hor_20230402190000.csv
pre_hor_20230402200000.csv
pre_hor_20230402210000.csv
pre_hor_20230402220000.csv
pre_hor_20230402230000.csv
pre_hor_20230403000000.csv
pre_hor_20230403010000.csv
pre_hor_20230403020000.csv
pre_hor_20230403030000.csv
pre_hor_20230403040000.csv
pre_hor_20230403050000.csv
pre_hor_20230403060000.csv
pre_hor_20230403070000.csv
pre_hor_20230403080000.csv
pre_hor_20230403090000.csv
pre_hor_20230403100000.csv
pre_hor_20230403110000.csv
pre_hor_20230403120000.csv
pre_hor_20230403130000.csv
pre_hor_20230403140000.csv
pre_hor_20230403150000.csv
pre_hor_20230403160000.csv
pre_hor_20230403170000.csv
pre_hor_20230403180000.csv
pre_hor_20230403190000.csv
pre_hor_20230403200000.csv
pre_hor_20230403210000.csv
pre_hor_20230403220000.csv
pre_hor_20230403230000.csv
pre_hor_20230404000000.csv
pre_hor_20230404010000.csv
pre_hor_20230404020000.csv
pre_hor_20230404030000.csv
pre_hor_20230404040000.csv
pre_hor_20230404050000.csv
pre_hor_20230404060000.csv
pre_hor_20230404070000.csv
pre_hor_20230404080000.csv
pre_hor_20230404090000.csv
pre_hor_20230404100000.csv
pre_hor_20230404110000.csv
pre_hor_20230404120000.csv
pre_hor_20230404130000.csv
pre_hor_20230404140000.csv
pre_hor_20230404150000.csv
pre_hor_20230404160000.csv
pre_hor_20230404170000.csv
pre_hor_20230404180000.csv
pre_hor_20230404190000.csv
pre_hor_20230404200000.csv
pre_hor_20230404210000.csv
pre_hor_20230404220000.csv
pre_hor_20230404230000.csv
pre_hor_20230405000000.csv
pre_hor_20230405010000.csv
pre_hor_20230405020000.csv
pre_hor_20230405030000.csv
pre_hor_20230405040000.csv
pre_hor_20230405050000.csv
pre_hor_20230405060000.csv
pre_hor_20230405070000.csv
pre_hor_20230405080000.csv
pre_hor_20230405090000.csv
pre_hor_20230405100000.csv
pre_hor_20230405110000.csv
pre_hor_20230405120000.csv
pre_hor_20230405130000.csv
pre_hor_20230405140000.csv
pre_hor_20230405150000.csv
pre_hor_20230405160000.csv
pre_hor_20230405170000.csv
pre_hor_20230405180000.csv
pre_hor_20230405190000.csv
pre_hor_20230405200000.csv
pre_hor_20230405210000.csv
pre_hor_20230405220000.csv
pre_hor_20230405230000.csv
pre_hor_20230406000000.csv
pre_hor_20230406010000.csv
pre_hor_20230406020000.csv
pre_hor_20230406030000.csv
pre_hor_20230406040000.csv
pre_hor_20230406050000.csv
pre_hor_20230406060000.csv
pre_hor_20230406070000.csv
pre_hor_20230406080000.csv
pre_hor_20230406090000.csv
pre_hor_20230406100000.csv
pre_hor_20230406110000.csv
pre_hor_20230406120000.csv
pre_hor_20230406130000.csv
pre_hor_20230406140000.csv
pre_hor_20230406150000.csv
pre_hor_20230406160000.csv
pre_hor_20230406170000.csv
pre_hor_20230406180000.csv
pre_hor_20230406190000.csv
pre_hor_20230406200000.csv
pre_hor_20230406210000.csv
pre_hor_20230406220000.csv
pre_hor_20230406230000.csv
pre_hor_20230407000000.csv
pre_hor_20230407010000.csv
pre_hor_20230407020000.csv
pre_hor_20230407030000.csv
pre_hor_20230407040000.csv
pre_hor_20230407050000.csv
pre_hor_20230407060000.csv
pre_hor_20230407070000.csv
pre_hor_20230407080000.csv
pre_hor_20230407090000.csv
pre_hor_20230407100000.csv
pre_hor_20230407110000.csv
pre_hor_20230407120000.csv
pre_hor_20230407130000.csv
pre_hor_20230407140000.csv
pre_hor_20230407150000.csv
pre_hor_20230407160000.csv
pre_hor_20230407170000.csv
pre_hor_20230407180000.csv
pre_hor_20230407190000.csv
pre_hor_20230407200000.csv
pre_hor_20230407210000.csv
pre_hor_20230407220000.csv
pre_hor_20230407230000.csv
pre_hor_20230408000000.csv
pre_hor_20230408010000.csv
pre_hor_20230408020000.csv
pre_hor_20230408030000.csv
pre_hor_20230408040000.csv
pre_hor_20230408050000.csv
pre_hor_20230408060000.csv
pre_hor_20230408070000.csv
pre_hor_20230408080000.csv
pre_hor_20230408090000.csv
pre_hor_20230408100000.csv
pre_hor_20230408110000.csv
pre_hor_20230408120000.csv
pre_hor_20230408130000.csv
pre_hor_20230408140000.csv
pre_hor_20230408150000.csv
pre_hor_20230408160000.csv
pre_hor_20230408170000.csv
pre_hor_20230408180000.csv
pre_hor_20230408190000.csv
pre_hor_20230408200000.csv
pre_hor_20230408210000.csv
pre_hor_20230408220000.csv
pre_hor_20230408230000.csv
pre_hor_20230409000000.csv
pre_hor_20230409010000.csv
pre_hor_20230409020000.csv
pre_hor_20230409030000.csv
pre_hor_20230409040000.csv
pre_hor_20230409050000.csv
pre_hor_20230409060000.csv
pre_hor_20230409070000.csv
pre_hor_20230409080000.csv
pre_hor_20230409090000.csv
pre_hor_20230409100000.csv
pre_hor_20230409110000.csv
pre_hor_20230409120000.csv
pre_hor_20230409130000.csv
pre_hor_20230409140000.csv
pre_hor_20230409150000.csv
pre_hor_20230409160000.csv
pre_hor_20230409170000.csv
pre_hor_20230409180000.csv
pre_hor_20230409190000.csv
pre_hor_20230409200000.csv
pre_hor_20230409210000.csv
pre_hor_20230409220000.csv
pre_hor_20230409230000.csv
pre_hor_20230410000000.csv
pre_hor_20230410010000.csv
pre_hor_20230410020000.csv
pre_hor_20230410030000.csv
pre_hor_20230410040000.csv
pre_hor_20230410050000.csv
pre_hor_20230410060000.csv
pre_hor_20230410070000.csv
pre_hor_20230410080000.csv
pre_hor_20230410090000.csv
pre_hor_20230410100000.csv
pre_hor_20230410110000.csv
pre_hor_20230410120000.csv
pre_hor_20230410130000.csv
pre_hor_20230410140000.csv
pre_hor_20230410150000.csv
pre_hor_20230410160000.csv
pre_hor_20230410170000.csv
pre_hor_20230410180000.csv
pre_hor_20230410190000.csv
pre_hor_20230410200000.csv
pre_hor_20230410210000.csv
pre_hor_20230410220000.csv
pre_hor_20230410230000.csv
pre_hor_20230411000000.csv
pre_hor_20230411010000.csv
pre_hor_20230411020000.csv
pre_hor_20230411030000.csv
pre_hor_20230411040000.csv
pre_hor_20230411050000.csv
pre_hor_20230411060000.csv
pre_hor_20230411070000.csv
pre_hor_20230411080000.csv
pre_hor_20230411090000.csv
pre_hor_20230411100000.csv
pre_hor_20230411110000.csv
pre_hor_20230411120000.csv
pre_hor_20230411130000.csv
pre_hor_20230411140000.csv
pre_hor_20230411150000.csv
pre_hor_20230411160000.csv
pre_hor_20230411170000.csv
pre_hor_20230411180000.csv
pre_hor_20230411190000.csv
pre_hor_20230411200000.csv
pre_hor_20230411210000.csv
pre_hor_20230411220000.csv
pre_hor_20230411230000.csv
pre_hor_20230412000000.csv
pre_hor_20230412010000.csv
pre_hor_20230412020000.csv
pre_hor_20230412030000.csv
pre_hor_20230412040000.csv
pre_hor_20230412050000.csv
pre_hor_20230412060000.csv
pre_hor_20230412070000.csv
pre_hor_20230412080000.csv
pre_hor_20230412090000.csv
pre_hor_20230412100000.csv
pre_hor_20230412110000.csv
pre_hor_20230412120000.csv
pre_hor_20230412130000.csv
pre_hor_20230412140000.csv
pre_hor_20230412150000.csv
pre_hor_20230412160000.csv
pre_hor_20230412170000.csv
pre_hor_20230412180000.csv
pre_hor_20230412190000.csv
pre_hor_20230412200000.csv
pre_hor_20230412210000.csv
pre_hor_20230412220000.csv
pre_hor_20230412230000.csv
pre_hor_20230413000000.csv
pre_hor_20230413010000.csv
pre_hor_20230413020000.csv
pre_hor_20230413030000.csv
pre_hor_20230413040000.csv
pre_hor_20230413050000.csv
pre_hor_20230413060000.csv
pre_hor_20230413070000.csv
pre_hor_20230413080000.csv
pre_hor_20230413090000.csv
pre_hor_20230413100000.csv
pre_hor_20230413110000.csv
pre_hor_20230413120000.csv
pre_hor_20230413130000.csv
pre_hor_20230413140000.csv
pre_hor_20230413150000.csv
pre_hor_20230413160000.csv
pre_hor_20230413170000.csv
pre_hor_20230413180000.csv
pre_hor_20230413190000.csv
pre_hor_20230413200000.csv
pre_hor_20230413210000.csv
pre_hor_20230413220000.csv
pre_hor_20230413230000.csv
pre_hor_20230414000000.csv
pre_hor_20230414010000.csv
pre_hor_20230414020000.csv
pre_hor_20230414030000.csv
pre_hor_20230414040000.csv
pre_hor_20230414050000.csv
pre_hor_20230414060000.csv
pre_hor_20230414070000.csv
pre_hor_20230414080000.csv
pre_hor_20230414090000.csv
pre_hor_20230414100000.csv
pre_hor_20230414110000.csv
pre_hor_20230414120000.csv
pre_hor_20230414130000.csv
pre_hor_20230414140000.csv
pre_hor_20230414150000.csv
pre_hor_20230414160000.csv
pre_hor_20230414170000.csv
pre_hor_20230414180000.csv
pre_hor_20230414190000.csv
pre_hor_20230414200000.csv
pre_hor_20230414210000.csv
pre_hor_20230414220000.csv
pre_hor_20230414230000.csv
pre_hor_20230415000000.csv
pre_hor_20230415010000.csv
pre_hor_20230415020000.csv
pre_hor_20230415030000.csv
pre_hor_20230415040000.csv
pre_hor_20230415050000.csv
pre_hor_20230415060000.csv
pre_hor_20230415070000.csv
pre_hor_20230415080000.csv
pre_hor_20230415090000.csv
pre_hor_20230415100000.csv
pre_hor_20230415110000.csv
pre_hor_20230415120000.csv
pre_hor_20230415130000.csv
pre_hor_20230415140000.csv
pre_hor_20230415150000.csv
pre_hor_20230415160000.csv
pre_hor_20230415170000.csv
pre_hor_20230415180000.csv
pre_hor_20230415190000.csv
pre_hor_20230415200000.csv
pre_hor_20230415210000.csv
pre_hor_20230415220000.csv
pre_hor_20230415230000.csv
pre_hor_20230416000000.csv
pre_hor_20230416010000.csv
pre_hor_20230416020000.csv
pre_hor_20230416030000.csv
pre_hor_20230416040000.csv
pre_hor_20230416050000.csv
pre_hor_20230416060000.csv
pre_hor_20230416070000.csv
pre_hor_20230416080000.csv
pre_hor_20230416090000.csv
pre_hor_20230416100000.csv
pre_hor_20230416110000.csv
pre_hor_20230416120000.csv
pre_hor_20230416130000.csv
pre_hor_20230416140000.csv
pre_hor_20230416150000.csv
pre_hor_20230416160000.csv
pre_hor_20230416170000.csv
pre_hor_20230416180000.csv
pre_hor_20230416190000.csv
pre_hor_20230416200000.csv
pre_hor_20230416210000.csv
pre_hor_20230416220000.csv
pre_hor_20230416230000.csv
pre_hor_20230417000000.csv
pre_hor_20230417010000.csv
pre_hor_20230417020000.csv
pre_hor_20230417030000.csv
pre_hor_20230417040000.csv
pre_hor_20230417050000.csv
pre_hor_20230417060000.csv
pre_hor_20230417070000.csv
pre_hor_20230417080000.csv
pre_hor_20230417090000.csv
pre_hor_20230417100000.csv
pre_hor_20230417110000.csv
pre_hor_20230417120000.csv
pre_hor_20230417130000.csv
pre_hor_20230417140000.csv
pre_hor_20230417150000.csv
pre_hor_20230417160000.csv
pre_hor_20230417170000.csv
pre_hor_20230417180000.csv
pre_hor_20230417190000.csv
pre_hor_20230417200000.csv
pre_hor_20230417210000.csv
pre_hor_20230417220000.csv
pre_hor_20230417230000.csv
pre_hor_20230418000000.csv
pre_hor_20230418010000.csv
pre_hor_20230418020000.csv
pre_hor_20230418030000.csv
pre_hor_20230418040000.csv
pre_hor_20230418050000.csv
pre_hor_20230418060000.csv
pre_hor_20230418070000.csv
pre_hor_20230418080000.csv
pre_hor_20230418090000.csv
pre_hor_20230418100000.csv
pre_hor_20230418110000.csv
pre_hor_20230418120000.csv
pre_hor_20230418130000.csv
pre_hor_20230418140000.csv
pre_hor_20230418150000.csv
pre_hor_20230418160000.csv
pre_hor_20230418170000.csv
pre_hor_20230418180000.csv
pre_hor_20230418190000.csv
pre_hor_20230418200000.csv
pre_hor_20230418210000.csv
pre_hor_20230418220000.csv
pre_hor_20230418230000.csv
pre_hor_20230419000000.csv
pre_hor_20230419010000.csv
pre_hor_20230419020000.csv
pre_hor_20230419030000.csv
pre_hor_20230419040000.csv
pre_hor_20230419050000.csv
pre_hor_20230419060000.csv
pre_hor_20230419070000.csv
pre_hor_20230419080000.csv
pre_hor_20230419090000.csv
pre_hor_20230419100000.csv
pre_hor_20230419110000.csv
pre_hor_20230419120000.csv
pre_hor_20230419130000.csv
pre_hor_20230419140000.csv
pre_hor_20230419150000.csv
pre_hor_20230419160000.csv
pre_hor_20230419170000.csv
pre_hor_20230419180000.csv
pre_hor_20230419190000.csv
pre_hor_20230419200000.csv
pre_hor_20230419210000.csv
pre_hor_20230419220000.csv
pre_hor_20230419230000.csv
pre_hor_20230420000000.csv
pre_hor_20230420010000.csv
pre_hor_20230420020000.csv
pre_hor_20230420030000.csv
pre_hor_20230420040000.csv
pre_hor_20230420050000.csv
pre_hor_20230420060000.csv
pre_hor_20230420070000.csv
pre_hor_20230420080000.csv
pre_hor_20230420090000.csv
pre_hor_20230420100000.csv
pre_hor_20230420110000.csv
pre_hor_20230420120000.csv
pre_hor_20230420130000.csv
pre_hor_20230420140000.csv
pre_hor_20230420150000.csv
pre_hor_20230420160000.csv
pre_hor_20230420170000.csv
pre_hor_20230420180000.csv
pre_hor_20230420190000.csv
pre_hor_20230420200000.csv
pre_hor_20230420210000.csv
pre_hor_20230420220000.csv
pre_hor_20230420230000.csv
pre_hor_20230421000000.csv
pre_hor_20230421010000.csv
pre_hor_20230421020000.csv
pre_hor_20230421030000.csv
pre_hor_20230421040000.csv
pre_hor_20230421050000.csv
pre_hor_20230421060000.csv
pre_hor_20230421070000.csv
pre_hor_20230421080000.csv
pre_hor_20230421090000.csv
pre_hor_20230421100000.csv
pre_hor_20230421110000.csv
pre_hor_20230421120000.csv
pre_hor_20230421130000.csv
pre_hor_20230421140000.csv
pre_hor_20230421150000.csv
pre_hor_20230421160000.csv
pre_hor_20230421170000.csv
pre_hor_20230421180000.csv
pre_hor_20230421190000.csv
pre_hor_20230421200000.csv
pre_hor_20230421210000.csv
pre_hor_20230421220000.csv
pre_hor_20230421230000.csv
pre_hor_20230422000000.csv
pre_hor_20230422010000.csv
pre_hor_20230422020000.csv
pre_hor_20230422030000.csv
pre_hor_20230422040000.csv
pre_hor_20230422050000.csv
pre_hor_20230422060000.csv
pre_hor_20230422070000.csv
pre_hor_20230422080000.csv
pre_hor_20230422090000.csv
pre_hor_20230422100000.csv
pre_hor_20230422110000.csv
pre_hor_20230422120000.csv
pre_hor_20230422130000.csv
pre_hor_20230422140000.csv
pre_hor_20230422150000.csv
pre_hor_20230422160000.csv
pre_hor_20230422170000.csv
pre_hor_20230422180000.csv
pre_hor_20230422190000.csv
pre_hor_20230422200000.csv
pre_hor_20230422210000.csv
pre_hor_20230422220000.csv
pre_hor_20230422230000.csv
pre_hor_20230423000000.csv
pre_hor_20230423010000.csv
pre_hor_20230423020000.csv
pre_hor_20230423030000.csv
pre_hor_20230423040000.csv
pre_hor_20230423050000.csv
pre_hor_20230423060000.csv
pre_hor_20230423070000.csv
pre_hor_20230423080000.csv
pre_hor_20230423090000.csv
pre_hor_20230423100000.csv
pre_hor_20230423110000.csv
pre_hor_20230423120000.csv
pre_hor_20230423130000.csv
pre_hor_20230423140000.csv
pre_hor_20230423150000.csv
pre_hor_20230423160000.csv
pre_hor_20230423170000.csv
pre_hor_20230423180000.csv
pre_hor_20230423190000.csv
pre_hor_20230423200000.csv
pre_hor_20230423210000.csv
pre_hor_20230423220000.csv
pre_hor_20230423230000.csv
pre_hor_20230424000000.csv
pre_hor_20230424010000.csv
pre_hor_20230424020000.csv
pre_hor_20230424030000.csv
pre_hor_20230424040000.csv
pre_hor_20230424050000.csv
pre_hor_20230424060000.csv
pre_hor_20230424070000.csv
pre_hor_20230424080000.csv
pre_hor_20230424090000.csv
pre_hor_20230424100000.csv
pre_hor_20230424110000.csv
pre_hor_20230424120000.csv
pre_hor_20230424130000.csv
pre_hor_20230424140000.csv
pre_hor_20230424150000.csv
pre_hor_20230424160000.csv
pre_hor_20230424170000.csv
pre_hor_20230424180000.csv
pre_hor_20230424190000.csv
pre_hor_20230424200000.csv
pre_hor_20230424210000.csv
pre_hor_20230424220000.csv
pre_hor_20230424230000.csv
pre_hor_20230425000000.csv
pre_hor_20230425010000.csv
pre_hor_20230425020000.csv
pre_hor_20230425030000.csv
pre_hor_20230425040000.csv
pre_hor_20230425050000.csv
pre_hor_20230425060000.csv
pre_hor_20230425070000.csv
pre_hor_20230425080000.csv
pre_hor_20230425090000.csv
pre_hor_20230425100000.csv
pre_hor_20230425110000.csv
pre_hor_20230425120000.csv
pre_hor_20230425130000.csv
pre_hor_20230425140000.csv
pre_hor_20230425150000.csv
pre_hor_20230425160000.csv
pre_hor_20230425170000.csv
pre_hor_20230425180000.csv
pre_hor_20230425190000.csv
pre_hor_20230425200000.csv
pre_hor_20230425210000.csv
pre_hor_20230425220000.csv
pre_hor_20230425230000.csv
pre_hor_20230426000000.csv
pre_hor_20230426010000.csv
pre_hor_20230426020000.csv
pre_hor_20230426030000.csv
pre_hor_20230426040000.csv
pre_hor_20230426050000.csv
pre_hor_20230426060000.csv
pre_hor_20230426070000.csv
pre_hor_20230426080000.csv
pre_hor_20230426090000.csv
pre_hor_20230426100000.csv
pre_hor_20230426110000.csv
pre_hor_20230426120000.csv
pre_hor_20230426130000.csv
pre_hor_20230426140000.csv
pre_hor_20230426150000.csv
pre_hor_20230426160000.csv
pre_hor_20230426170000.csv
pre_hor_20230426180000.csv
pre_hor_20230426190000.csv
pre_hor_20230426200000.csv
pre_hor_20230426210000.csv
pre_hor_20230426220000.csv
pre_hor_20230426230000.csv
pre_hor_20230427000000.csv
pre_hor_20230427010000.csv
pre_hor_20230427020000.csv
pre_hor_20230427030000.csv
pre_hor_20230427040000.csv
pre_hor_20230427050000.csv
pre_hor_20230427060000.csv
pre_hor_20230427070000.csv
pre_hor_20230427080000.csv
pre_hor_20230427090000.csv
pre_hor_20230427100000.csv
pre_hor_20230427110000.csv
pre_hor_20230427120000.csv
pre_hor_20230427130000.csv
pre_hor_20230427140000.csv
pre_hor_20230427150000.csv
pre_hor_20230427160000.csv
pre_hor_20230427170000.csv
pre_hor_20230427180000.csv
pre_hor_20230427190000.csv
pre_hor_20230427200000.csv
pre_hor_20230427210000.csv
pre_hor_20230427220000.csv
pre_hor_20230427230000.csv
pre_hor_20230428000000.csv
pre_hor_20230428010000.csv
pre_hor_20230428020000.csv
pre_hor_20230428030000.csv
pre_hor_20230428040000.csv
pre_hor_20230428050000.csv
pre_hor_20230428060000.csv
pre_hor_20230428070000.csv
pre_hor_20230428080000.csv
pre_hor_20230428090000.csv
pre_hor_20230428100000.csv
pre_hor_20230428110000.csv
pre_hor_20230428120000.csv
pre_hor_20230428130000.csv
pre_hor_20230428140000.csv
pre_hor_20230428150000.csv
pre_hor_20230428160000.csv
pre_hor_20230428170000.csv
pre_hor_20230428180000.csv
pre_hor_20230428190000.csv
pre_hor_20230428200000.csv
pre_hor_20230428210000.csv
pre_hor_20230428220000.csv
pre_hor_20230428230000.csv
pre_hor_20230429000000.csv
pre_hor_20230429010000.csv
pre_hor_20230429020000.csv
pre_hor_20230429030000.csv
pre_hor_20230429040000.csv
pre_hor_20230429050000.csv
pre_hor_20230429060000.csv
pre_hor_20230429070000.csv
pre_hor_20230429080000.csv
pre_hor_20230429090000.csv
pre_hor_20230429100000.csv
pre_hor_20230429110000.csv
pre_hor_20230429120000.csv
pre_hor_20230429130000.csv
pre_hor_20230429140000.csv
pre_hor_20230429150000.csv
pre_hor_20230429160000.csv
pre_hor_20230429170000.csv
pre_hor_20230429180000.csv
pre_hor_20230429190000.csv
pre_hor_20230429200000.csv
pre_hor_20230429210000.csv
pre_hor_20230429220000.csv
pre_hor_20230429230000.csv
pre_hor_20230430000000.csv
pre_hor_20230430010000.csv
pre_hor_20230430020000.csv
pre_hor_20230430030000.csv
pre_hor_20230430040000.csv
pre_hor_20230430050000.csv
pre_hor_20230430060000.csv
pre_hor_20230430070000.csv
pre_hor_20230430080000.csv
pre_hor_20230430090000.csv
pre_hor_20230430100000.csv
pre_hor_20230430110000.csv
pre_hor_20230430120000.csv
pre_hor_20230430130000.csv
pre_hor_20230430140000.csv
pre_hor_20230430150000.csv
pre_hor_20230430160000.csv
pre_hor_20230430170000.csv
pre_hor_20230430180000.csv
pre_hor_20230430190000.csv
pre_hor_20230430200000.csv
pre_hor_20230430210000.csv
pre_hor_20230430220000.csv
pre_hor_20230430230000.csv
pre_hor_20230501000000.csv
pre_hor_20230501010000.csv
pre_hor_20230501020000.csv
pre_hor_20230501030000.csv
pre_hor_20230501040000.csv
pre_hor_20230501050000.csv
pre_hor_20230501060000.csv
pre_hor_20230501070000.csv
pre_hor_20230501080000.csv
pre_hor_20230501090000.csv
pre_hor_20230501100000.csv
pre_hor_20230501110000.csv
pre_hor_20230501120000.csv
pre_hor_20230501130000.csv
pre_hor_20230501140000.csv
pre_hor_20230501150000.csv
pre_hor_20230501160000.csv
pre_hor_20230501170000.csv
pre_hor_20230501180000.csv
pre_hor_20230501190000.csv

In [6]:
new_lons

[112.0322,
 115.795,
 115.48,
 119.16,
 113.1056,
 113.5719,
 114.6381,
 120.0744,
 113.805,
 119.0964,
 112.6253,
 114.3494,
 113.4792,
 119.4572,
 119.9794,
 111.5603,
 111.6122,
 112.27,
 118.92,
 121.1075,
 116.7283,
 120.4397,
 120.2239,
 113.9283,
 114.6461,
 119.7728,
 111.8239,
 114.3467,
 120.2161,
 114.3578,
 111.4428,
 115.0914,
 119.5047,
 114.4914,
 119.8208,
 112.7447,
 118.735,
 117.9447,
 118.8511,
 114.3228,
 113.9414,
 113.4322,
 113.5511,
 113.515,
 112.975,
 121.3378,
 118.0742,
 117.8586,
 117.2047,
 119.4058,
 114.9422,
 115.8056,
 115.4164,
 117.8731,
 114.4569,
 120.8444,
 113.4958,
 117.4283,
 115.5494,
 114.2236,
 112.6986,
 112.3578,
 111.7275,
 121.4869,
 115.1222,
 114.0539,
 116.7594,
 113.1339,
 111.6864,
 119.7983,
 116.94,
 113.2144,
 115.0931,
 118.8067,
 119.8928,
 120.4111,
 115.2789,
 111.2189,
 114.3247,
 111.0294,
 121.3022,
 113.9189,
 114.4425,
 114.3225,
 113.5292,
 112.2461,
 113.8758,
 119.1481,
 119.8728,
 120.0097,
 120.3094,
 115.8531,
 114.2256,
 111.2336,
 112.9339,
 113.9911,
 114.7064,
 114.2056,
 119.3103,
 120.0392,
 120.2992,
 118.0478,
 121.4211,
 119.9722,
 119.7244,
 118.1914,
 111.7319,
 121.1217,
 120.8386,
 115.9278,
 116.1456,
 118.9994,
 115.23,
 114.0314,
 119.4244,
 117.9642,
 111.4003,
 120.4981,
 118.5211,
 113.3547,
 114.6439,
 118.8947,
 111.2428,
 112.505,
 120.7297,
 112.8222,
 112.3161,
 115.4322,
 111.2897,
 113.6622,
 118.6192,
 121.4186,
 120.2167,
 117.8228,
 113.0572,
 120.3711,
 120.1575,
 119.315,
 111.6214,
 116.4436,
 116.5631,
 112.9983,
 121.1614,
 120.1719,
 113.5603,
 118.6567,
 114.5758,
 111.0158,
 119.2903,
 113.7189,
 118.3828,
 113.9658,
 119.8172,
 118.9,
 114.6406,
 117.2931,
 116.2694,
 114.225,
 120.7364,
 111.2894,
 116.8333,
 111.8253,
 119.9767,
 118.8881,
 120.4844,
 114.0889,
 119.9578,
 119.1511,
 112.7572,
 112.6797,
 120.52,
 113.7167,
 114.1589,
 121.9806,
 112.0067,
 116.9447,
 120.7606,
 114.4847,
 117.8511,
 119.37,
 113.3033,
 119.1647,
 111.0972,
 112.6775,
 117.9,
 119.47,
 114.3361,
 120.215,
 120.2853,
 119.4186,
 119.0169,
 119.8306,
 115.6667,
 117.0683,
 115.1164,
 114.1075,
 120.4739,
 120.1275,
 111.2242,
 114.7269,
 112.5761,
 114.7022,
 113.1681,
 114.5825,
 113.6906,
 118.2717,
 121.3403,
 113.9425,
 120.7453,
 114.4967,
 111.4711,
 118.9578,
 111.9539,
 120.11,
 114.0064,
 121.1539,
 117.9436,
 112.3692,
 118.8508,
 119.7514,
 117.7006,
 115.4278,
 113.8606,
 114.0397,
 117.9044,
 120.33,
 116.345,
 118.1722,
 113.255,
 117.8394,
 113.8081,
 120.4928,
 120.1039,
 118.5339,
 116.175,
 118.2492,
 112.215,
 119.4358,
 111.17,
 117.8222,
 119.7833,
 114.8428,
 118.7347,
 119.6253,
 114.2439,
 114.1722,
 114.5003,
 119.5017,
 119.6786,
 119.2189,
 113.6717,
 112.1261,
 120.6914,
 115.365,
 120.4903,
 119.3467,
 118.385,
 118.2153,
 118.1403,
 114.7739,
 121.5575,
 117.2633,
 113.5961,
 120.4683,
 118.1739,
 117.0114,
 115.0197,
 117.6981,
 118.5283,
 113.3303,
 112.4933,
 120.5111,
 113.3608,
 118.8239,
 114.92,
 118.6375,
 111.0792,
 119.3758,
 115.8225,
 120.2653,
 113.8336,
 116.7619,
 120.6078,
 114.9794,
 119.5706,
 119.9861,
 114.4836,
 120.4592,
 119.9933,
 112.8758,
 113.2625,
 115.2969,
 120.6183,
 117.1306,
 119.7367,
 120.855,
 113.3742,
 116.4247,
 121.1725,
 117.9725,
 119.1136,
 116.0031,
 111.4761,
 112.5606,
 119.3614,
 115.3097,
 114.0172,
 114.1781,
 113.4578,
 112.8594,
 116.3819,
 111.7539,
 120.945,
 111.0792,
 117.4556,
 111.9117,
 120.1164,
 114.8153,
 111.5467,
 116.9778,
 114.0703,
 116.4592,
 112.1508,
 116.8875,
 121.1311,
 112.8033,
 111.7317,
 113.7853,
 115.1153,
 111.575,
 115.9328,
 120.68,
 114.8756,
 119.4642,
 113.7164,
 115.3914,
 111.3786,
 116.8222,
 113.0661,
 115.0156,
 120.1858,
 119.9125,
 112.1372,
 118.5461,
 114.825,
 121.0853,
 112.4997,
 117.4753,
 114.2147,
 120.0872,
 111.7581,
 120.4472,
 111.4969,
 113.9914,
 114.6147,
 113.5642,
 115.7103,
 113.3075,
 111.3158,
 120.3708,
 115.4103,
 111.1814,
 117.6444,
 113.0919,
 118.6597,
 112.7953,
 118.0319,
 119.9244,
 111.8714,
 114.1542,
 117.5719,
 112.6703,
 119.1797,
 119.6703,
 116.7569,
 113.7806,
 118.7417,
 115.9225,
 117.14,
 120.4439,
 120.3992,
 120.3289,
 121.1217,
 111.6017,
 119.6333,
 119.0419,
 117.9797,
 118.3622,
 115.2539,
 115.1242,
 111.0444,
 118.1289,
 119.3642,
 118.3478,
 116.2631,
 115.8681,
 121.4153,
 111.6994,
 119.96,
 111.7461,
 119.9911,
 119.6506,
 112.5894,
 120.2272,
 115.695,
 119.98,
 119.5694,
 119.7089,
 113.0539,
 120.1992,
 111.3725,
 120.2242,
 119.0444,
 111.6403,
 116.3725,
 120.6872,
 118.6961,
 116.4244,
 120.725,
 112.9139,
 118.0847,
 118.4561,
 112.3494,
 114.2747,
 111.3378,
 113.0414,
 119.0586,
 114.2869,
 117.8647,
 118.9011,
 119.1425,
 121.5233,
 111.1153,
 120.9178,
 121.5347,
 113.0186,
 117.3153,
 112.8272,
 114.5128,
 112.3833,
 118.9808,
 113.0542,
 120.6222,
 118.6031,
 119.0353,
 118.7831,
 114.08,
 120.745,
 112.8433,
 115.4447,
 114.7028,
 114.4103,
 116.4372,
 118.6956,
 114.8758,
 118.5606,
 111.4183,
 113.2981,
 119.3519,
 115.1194,
 117.4011,
 114.6356,
 116.1569,
 120.9039,
 114.36,
 119.8661,
 112.5719,
 120.4547,
 120.8058,
 113.0942,
 119.3161,
 121.2194,
 113.6933,
 115.3261,
 113.0825,
 116.7492,
 120.3742,
 112.7361,
 118.9381,
 115.18,
 119.1017,
 120.4222,
 118.3058,
 113.6886,
 115.1356,
 119.8225,
 120.6786,
 119.9169,
 120.4978,
 112.9689,
 114.5856,
 121.1622,
 112.7186,
 112.2689,
 120.0478,
 113.9428,
 118.0972,
 116.0606,
 116.4808,
 112.9831,
 113.6747,
 113.4444,
 113.5572,
 117.2997,
 116.7814,
 120.8164,
 116.2019,
 114.2114,
 111.6917,
 118.9342,
 118.5689,
 112.3756,
 113.9144,
 112.8703,
 117.1656,
 120.8044,
 119.3797,
 112.6811,
 115.1431,
 119.5781,
 114.6344,
 119.8147,
 114.2764,
 118.5467,
 112.3953,
 114.5658,
 118.9647,
 119.1572,
 120.5883,
 113.6808,
 111.9783,
 121.2267,
 120.6117,
 121.0861,
 120.1781,
 112.3614,
 115.11,
 118.9614,
 115.5747,
 118.52,
 113.0889,
 114.5942,
 112.7058,
 118.6858,
 113.5403,
 114.9031,
 115.9528,
 115.51,
 117.7497,
 111.9539,
 116.335,
 113.0572,
 120.4383,
 114.4983,
 119.9136,
 114.2292,
 119.3164,
 118.4744,
 121.4928,
 111.79,
 121.2486,
 120.1553,
 113.0981,
 120.1917,
 113.8322,
 112.4042,
 111.7228,
 119.5511,
 111.3178,
 119.4603,
 116.305,
 115.4911,
 114.1217,
 113.6753,
 114.335,
 112.7864,
 115.9867,
 113.6458,
 120.3,
 119.3397,
 115.8972,
 117.0731,
 111.6933,
 118.3214,
 119.3025,
 113.1414,
 111.3511,
 118.05,
 111.2908,
 120.7639,
 117.2714,
 120.3944,
 120.0694,
 118.2406,
 111.9172,
 118.3939,
 118.5947,
 114.5642,
 111.2675,
 120.9975,
 120.0142,
 114.2483,
 117.6831,
 119.5114,
 116.9239,
 113.4058,
 114.4775,
 120.4528,
 111.3908,
 120.1419,
 118.1467,
 113.1303,
 119.7547,
 113.205,
 119.3642,
 119.5931,
 112.4311,
 114.3556,
 116.2525,
 116.4111,
 119.9942,
 120.1958,
 113.8625,
 120.72,
 118.9933,
 114.1083,
 114.7108,
 120.5756,
 112.6453,
 113.3681,
 112.3256,
 120.1558,
 120.3206,
 113.8117,
 115.5228,
 117.1336,
 120.4022,
 112.8375,
 121.1742,
 115.6264,
 113.5033,
 112.4558,
 115.5886,
 115.8881,
 114.9217,
 112.2128,
 111.2708,
 121.6222,
 121.5411,
 113.0483,
 115.1903,
 120.5167,
 117.2139,
 113.8567,
 121.1997,
 114.7028,
 113.2817,
 121.1853,
 118.5017,
 119.2025,
 120.5931,
 120.9847,
 120.5028,
 111.0278,
 114.4131,
 116.965,
 117.8881,
 113.6139,
 116.8067,
 115.0092,
 118.7903,
 114.0969,
 112.1681,
 120.9236,
 121.0836,
 119.2417,
 115.8919,
 116.6644,
 117.7058,
 114.8631,
 114.3011,
 118.8789,
 112.1422,
 114.2092,
 113.7606,
 111.4319,
 112.5369,
 119.6472,
 112.3839,
 119.5508,
 119.39,
 114.8731,
 114.8772,
 119.8014,
 120.3964,
 111.3872,
 118.8233,
 120.0686,
 119.9933,
 111.9075,
 118.8953,
 112.2831,
 113.3403,
 117.3578,
 115.0789,
 121.3042,
 119.0725,
 115.645,
 116.2619,
 113.7811,
 115.8956,
 119.3094,
 115.1806,
 121.4861,
 119.6575,
 114.6381,
 117.8144,
 120.0942,
 115.8911,
 119.3344,
 120.9342,
 118.7911,
 113.4617,
 112.1431,
 114.325,
 112.1103,
 120.2297,
 111.5828,
 113.755,
 111.9044,
 115.0681,
 119.6844,
 112.7164,
 117.1183,
 111.7,
 120.5192,
 120.055,
 119.9106,
 113.0053,
 115.7364,
 112.4536,
 118.2719,
 112.3136,
 118.8139,
 115.2522,
 119.8111,
 114.8606,
 120.2261,
 119.4117,
 112.5797,
 119.1108,
 113.8542,
 118.8325,
 114.0764,
 112.22,
 114.235,
 116.0747,
 112.4556,
 113.5664,
 111.3622,
 111.3883,
 120.5219,
 117.6089,
 120.0336,
 113.0092,
 120.5628,
 119.7036,
 112.5314,
 115.2078,
 120.9025,
 115.6892,
 111.6847,
 117.265,
 118.4083,
 115.51,
 114.4117,
 118.5519,
 111.8889,
 118.9456,
 117.1669,
 111.2453,
 115.1708,
 113.0108,
 113.2922,
 115.5633,
 118.8422,
 114.2642,
 119.0367,
 114.7778,
 115.6144,
 119.7769,
 112.38,
 120.0964,
 119.2919,
 113.6867,
 120.0436,
 116.5958,
 115.7619,
 115.2781,
 119.9225,
 114.41,
 113.7989,
 112.6556,
 120.0208,
 112.0439,
 113.0503,
 116.7894,
 114.43,
 115.6661,
 120.6011,
 121.2331,
 111.5783,
 111.9078,
 114.4167,
 114.2636,
 112.4669,
 121.6206,
 120.8433,
 116.0547,
 112.72,
 121.3447,
 120.9672,
 115.2897,
 115.9689,
 121.52,
 120.8458,
 115.1894,
 113.2667,
 112.2161,
 120.9522,
 115.1894,
 121.8417,
 115.1217,
 114.6508,
 113.1192,
 119.8981,
 117.7008,
 115.9789,
 120.1986,
 120.0872,
 120.1756,
 116.6675,
 117.6717,
 118.2411,
 114.8392,
 114.2756,
 114.8319,
 119.8847,
 120.3008,
 113.2172,
 119.3767,
 120.5078,
 113.8064,
 114.9303,
 119.7156,
 113.7264,
 119.8381,
 111.0244,
 115.3075,
 115.1167,
 111.5783,
 113.5692,
 112.2936,
 121.1222,
 120.7894,
 112.1264,
 113.815,
 119.4794,
 119.0647,
 117.3181,
 112.5281,
 120.1197,
 115.0017,
 112.8331,
 113.5181,
 115.9706,
 112.9383,
 118.9956,
 121.1606,
 114.3928,
 114.5575,
 120.1747,
 113.9389,
 119.3803,
 115.2783,
 115.8817,
 111.8686,
 112.7547,
 112.9967,
 120.2931,
 119.8578,
 119.4042,
 118.8992,
 111.35,
 117.1586,
 116.7783,
 120.2167,
 120.9725,
 111.0186,
 120.0142,
 111.4867,
 121.4153,
 111.5028,
 117.3322,
 111.45,
 120.1169,
 121.4919,
 121.3328,
 114.7833,
 119.9486,
 113.3919,
 117.0714,
 119.8639,
 111.6039,
 114.7731,
 114.0972,
 120.5911,
 118.6764,
 120.0244,
 120.6853,
 114.1797,
 120.1283,
 117.5067,
 118.7578,
 119.6731,
 118.4478,
 111.7247,
 119.1775,
 111.7603,
 113.0925,
 119.6078,
 118.8028,
 112.2097,
 116.9033,
 114.6806,
 112.0286,
 114.1353,
 111.1869,
 112.2608,
 114.6922,
 118.4733,
 114.2308,
 121.3356,
 120.3889,
 114.5886,
 121.3547,
 121.4758,
 119.8861,
 111.7558,
 117.7739,
 118.4058,
 121.5606,
 120.0525,
 112.7592,
 115.4736,
 112.9894,
 115.1917,
 111.7839,
 119.9981,
 112.5881,
 120.6036,
 118.7542,
 113.7642,
 112.8542,
 121.0283,
 119.7333,
 117.0706,
 115.8758,
 111.7539,
 113.0169,
 120.1725,
 119.8139,
 112.6014,
 120.4894,
 119.9739,
 113.2278,
 112.9794,
 113.3294,
 113.2322,
 113.7483,
 120.3364,
 119.6203,
 121.0969,
 114.1144,
 119.5528,
 113.0383,
 118.1489,
 118.2908,
 111.3286,
 113.5006,
 115.2325,
 121.0378,
 115.9528,
 118.4806,
 114.6778,
 111.46,
 121.8786,
 121.4225,
 114.2592,
 111.0728,
 ...]

In [25]:
fenbian=1#0.1
p=int(7/fenbian)
q=int(11/fenbian)
num=np.zeros((p,q))
for i in range(len(new_lons)):
    x=int((new_lons[i]-111)/fenbian)
    y=int((new_lats[i]-30)/fenbian)
    num[y,x]=num[y,x]+1

In [40]:
df_num = pd.DataFrame(columns=['indexi', 'indexj', 'num'])
for i in range(len(new_lons)):
    x=int((new_lons[i]-111)/fenbian)
    y=int((new_lats[i]-30)/fenbian)
    condition = (df_num['indexi'] == y) & (df_num['indexj'] == x)
    
    if df_num[condition].empty:
        # 如果记录不存在，添加新的记录
        new_row = pd.DataFrame({'indexi': [y], 'indexj': [x], 'num': [1]})
        df_num = pd.concat([df_num, new_row], ignore_index=True)
    else:
        # 如果记录存在，更新计数
        df_num.loc[condition, 'num'] += 1

In [41]:
new_lats=np.array(new_lats)
new_lons=np.array(new_lons)
df_lonlats =pd.DataFrame({'indexi':((new_lats-30)/fenbian).astype(int),
					'indexj':((new_lons-111)/fenbian).astype(int),
                    'lons':new_lons,'lats':new_lats,
					})

In [42]:
df_posi = pd.merge(df_lonlats, df_num, on=['indexi', 'indexj'], how='outer')

In [4]:
# df_posi.to_csv('df_posi_1.csv',index=False)
df_posi=pd.read_csv('df_posi_01.csv')
df_posi

      indexi  indexj      lons     lats  num
0          0       3  111.3681  30.0397    1
1          0       5  111.5281  30.0433    1
2          0       8  111.8453  30.0286    1
3          0      12  112.2150  30.0744    1
4          0      15  112.5233  30.0953    1
...      ...     ...       ...      ...  ...
3457      69      81  119.1600  36.9431    1
3458      69      94  120.4439  36.9636    1
3459      69      97  120.7200  36.9717    2
3460      69      97  120.7444  36.9114    2
3461      69     107  121.7578  36.9103    1

[3462 rows x 5 columns]

In [8]:
df_reset

        station province cnty       lon      lat       pre
0        宁洛K256      安徽省  蒙城县  116.6983  33.1431       0.0
1        连云东辛农场      江苏省  市辖区  119.3094  34.5614       0.0
2           狼城岗      河南省  中牟县  114.1297  34.8331       0.0
3            韩寺      河南省  中牟县  114.1347  34.6258       0.0
4            石象      河南省  长葛市  113.8681  34.1922       0.0
...         ...      ...  ...       ...      ...       ...
13958        石弓      安徽省  涡阳县  116.3844  33.6947       0.0
13959        园林      湖北省  潜江市  112.8725  30.4350       0.0
13960  蚌合下行K119      安徽省  长丰县  117.1011  31.9922  999999.0
13961        阚疃      安徽省  利辛县  116.2814  33.0181       0.0
13962    汶上阳城煤矿      山东省  汶上县  116.3192  35.7714       0.0

[13963 rows x 6 columns]

In [29]:
df_staname=pd.merge(df_reset,df_posi,how='inner',left_on=['lon','lat'],right_on=['lons','lats'])

In [43]:
df_staname[ (df_staname['city']=='黄山市')]

,station,province,cnty,lon,lat,pre,city,indexi,indexj,lons,lats,num
2789,黄山,安徽省,黄山区,118.1642,30.1347,0.0,黄山市,1,71,118.1642,30.1347,1

In [46]:
df_staname[(df_staname['cnty']=='安泽县')]

,station,province,cnty,lon,lat,pre,city,indexi,indexj,lons,lats,num
138,安泽下场,山西省,安泽县,112.2300,36.2658,0.0,临汾市,62,12,112.2300,36.2658,2
139,安泽良马,山西省,安泽县,112.4350,36.2189,0.0,临汾市,62,14,112.4350,36.2189,1
493,安泽沁河庄,山西省,安泽县,112.2586,36.2839,0.0,临汾市,62,12,112.2586,36.2839,2
1130,安泽三交,山西省,安泽县,112.1264,36.4431,0.0,临汾市,64,11,112.1264,36.4431,1
2016,安泽郭都,山西省,安泽县,112.4997,36.1714,0.0,临汾市,61,14,112.4997,36.1714,1
3375,安泽和平,山西省,安泽县,112.2678,36.0928,0.0,临汾市,60,12,112.2678,36.0928,1